Rails.application.routes.draw do
  namespace :api do
    resources :persons, only: [:index, :show]
    resources :observation_periods, only: [:index, :show]
    resources :visit_occurrences, only: [:index, :show]
    resources :visit_details, only: [:index, :show]
    resources :condition_occurrences, only: [:index, :show]
    resources :drug_exposures, only: [:index, :show]
    resources :procedure_occurrences, only: [:index, :show]
    resources :device_exposures, only: [:index, :show]
    resources :measurements, only: [:index, :show]
    resources :observations, only: [:index, :show]
    resources :notes, only: [:index, :show]
    resources :note_nlps, only: [:index, :show]
    resources :specimens, only: [:index, :show]
    resources :deaths, only: [:index, :show]
    resources :locations, only: [:index, :show]
    resources :care_sites, only: [:index, :show]
    resources :providers, only: [:index, :show]
    resources :payer_plan_periods, only: [:index, :show]
    resources :costs, only: [:index, :show]
    resources :drug_eras, only: [:index, :show]
    resources :dose_eras, only: [:index, :show]
    resources :condition_eras, only: [:index, :show]
    resources :episodes, only: [:index, :show]
    resources :episode_events, only: [:index, :show]
    resources :metadata, only: [:index, :show]
    resources :cdm_sources, only: [:index, :show]
  end
end
